import {ReactNode} from 'react'
import type {Metadata} from 'next'
import {Roboto} from 'next/font/google'
import './globals.css'

const inter = Roboto({weight: '400', subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Preference Selector',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: Readonly<{
    children: ReactNode
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    )
}
